jetracer_controller_node:
  ros__parameters:
    serial_port: /dev/ttyACM0
    baud_rate: 115200
    kp: 350
    ki: 120
    kd: 0
    linear_correction: 1.0
    servo_bias: 0
    a: -0.016073
    b: 0.176183
    c: -23.428084
    d: 1500.0
    mock: true
